app:
  name: FilmFolk
  port: 8080

db:
  host: localhost
  port: 3432
  user: ravflyin
  password: ""
  dbname: FilmFolk
  sslmode: disable

jwt:
  secret: "a_very_long_and_random_secret_string_for_signing_tokens"