app:
  name: FilmFolk
  port: 8080
  env: development

db:
  host: localhost
  port: 5432
  user: ravflyin
  password: ""
  dbname: filmfolk
  sslmode: disable

jwt:
  secret: "a_very_long_and_random_secret_string_for_signing_tokens"
  access_token_ttl: 15  # minutes
  refresh_token_ttl: 7  # days

oauth:
  google_client_id: ""
  google_client_secret: ""
  google_redirect_url: "http://localhost:8080/auth/google/callback"
  facebook_client_id: ""
  facebook_client_secret: ""
  facebook_redirect_url: "http://localhost:8080/auth/facebook/callback"

tmdb:
  api_key: ""  # Get from https://www.themoviedb.org/settings/api

ai:
  openai_key: ""  # Get from https://platform.openai.com/api-keys